# Generated by Django 3.1.7 on 2021-05-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='mtest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
