# Generated by Django 3.1.7 on 2021-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210514_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'online'), ('cod', 'cod')], max_length=100, null=True),
        ),
    ]
