# Generated by Django 3.1.7 on 2021-05-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'online'), ('cod', 'cod')], default='cod', max_length=100, null=True),
        ),
    ]
