# Generated by Django 3.1.7 on 2021-05-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210518_1722'),
        ('users', '0007_auto_20210518_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cart_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.attributes'),
        ),
        migrations.AddField(
            model_name='payment',
            name='main_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
