# Generated by Django 3.1.7 on 2021-05-06 13:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210506_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
