# Generated by Django 3.1.7 on 2021-05-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_attributes_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='check',
            field=models.CharField(choices=[('yes', 'y'), ('no', 'n')], default='y', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='check',
            field=models.CharField(choices=[('yes', 'y'), ('no', 'n')], default='y', max_length=20),
        ),
    ]
