# Generated by Django 3.1.7 on 2021-05-18 07:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210514_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='check',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='check',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=20),
        ),
    ]
