# Generated by Django 3.1.7 on 2021-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210518_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='check',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='check',
            field=models.CharField(max_length=20),
        ),
    ]
