# Generated by Django 3.1.7 on 2021-05-19 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='rec1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec1', to='product.product'),
        ),
        migrations.AddField(
            model_name='rec',
            name='rec2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec2', to='product.product'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='product.product'),
        ),
    ]
