# Generated by Django 3.1.7 on 2021-05-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210519_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='rec2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rec2', to='product.product'),
        ),
    ]
